# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: evmos/claims/v1/genesis.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from evmosproto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from evmosproto.evmos.claims.v1 import claims_pb2 as evmos_dot_claims_dot_v1_dot_claims__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='evmos/claims/v1/genesis.proto',
  package='evmos.claims.v1',
  syntax='proto3',
  serialized_options=b'Z\'github.com/tharsis/evmos/x/claims/types',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1d\x65vmos/claims/v1/genesis.proto\x12\x0f\x65vmos.claims.v1\x1a\x14gogoproto/gogo.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1c\x65vmos/claims/v1/claims.proto\"\x81\x01\n\x0cGenesisState\x12-\n\x06params\x18\x01 \x01(\x0b\x32\x17.evmos.claims.v1.ParamsB\x04\xc8\xde\x1f\x00\x12\x42\n\x0e\x63laims_records\x18\x02 \x03(\x0b\x32$.evmos.claims.v1.ClaimsRecordAddressB\x04\xc8\xde\x1f\x00\"\xfa\x01\n\x06Params\x12\x15\n\renable_claims\x18\x01 \x01(\x08\x12@\n\x12\x61irdrop_start_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x08\xc8\xde\x1f\x00\x90\xdf\x1f\x01\x12\x41\n\x14\x64uration_until_decay\x18\x03 \x01(\x0b\x32\x19.google.protobuf.DurationB\x08\xc8\xde\x1f\x00\x98\xdf\x1f\x01\x12>\n\x11\x64uration_of_decay\x18\x04 \x01(\x0b\x32\x19.google.protobuf.DurationB\x08\xc8\xde\x1f\x00\x98\xdf\x1f\x01\x12\x14\n\x0c\x63laims_denom\x18\x05 \x01(\tB)Z\'github.com/tharsis/evmos/x/claims/typesb\x06proto3'
  ,
  dependencies=[gogoproto_dot_gogo__pb2.DESCRIPTOR,google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,evmos_dot_claims_dot_v1_dot_claims__pb2.DESCRIPTOR,])




_GENESISSTATE = _descriptor.Descriptor(
  name='GenesisState',
  full_name='evmos.claims.v1.GenesisState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='params', full_name='evmos.claims.v1.GenesisState.params', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='claims_records', full_name='evmos.claims.v1.GenesisState.claims_records', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=297,
)


_PARAMS = _descriptor.Descriptor(
  name='Params',
  full_name='evmos.claims.v1.Params',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='enable_claims', full_name='evmos.claims.v1.Params.enable_claims', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='airdrop_start_time', full_name='evmos.claims.v1.Params.airdrop_start_time', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000\220\337\037\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='duration_until_decay', full_name='evmos.claims.v1.Params.duration_until_decay', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000\230\337\037\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='duration_of_decay', full_name='evmos.claims.v1.Params.duration_of_decay', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000\230\337\037\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='claims_denom', full_name='evmos.claims.v1.Params.claims_denom', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=300,
  serialized_end=550,
)

_GENESISSTATE.fields_by_name['params'].message_type = _PARAMS
_GENESISSTATE.fields_by_name['claims_records'].message_type = evmos_dot_claims_dot_v1_dot_claims__pb2._CLAIMSRECORDADDRESS
_PARAMS.fields_by_name['airdrop_start_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_PARAMS.fields_by_name['duration_until_decay'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_PARAMS.fields_by_name['duration_of_decay'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
DESCRIPTOR.message_types_by_name['GenesisState'] = _GENESISSTATE
DESCRIPTOR.message_types_by_name['Params'] = _PARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenesisState = _reflection.GeneratedProtocolMessageType('GenesisState', (_message.Message,), {
  'DESCRIPTOR' : _GENESISSTATE,
  '__module__' : 'evmos.claims.v1.genesis_pb2'
  # @@protoc_insertion_point(class_scope:evmos.claims.v1.GenesisState)
  })
_sym_db.RegisterMessage(GenesisState)

Params = _reflection.GeneratedProtocolMessageType('Params', (_message.Message,), {
  'DESCRIPTOR' : _PARAMS,
  '__module__' : 'evmos.claims.v1.genesis_pb2'
  # @@protoc_insertion_point(class_scope:evmos.claims.v1.Params)
  })
_sym_db.RegisterMessage(Params)


DESCRIPTOR._options = None
_GENESISSTATE.fields_by_name['params']._options = None
_GENESISSTATE.fields_by_name['claims_records']._options = None
_PARAMS.fields_by_name['airdrop_start_time']._options = None
_PARAMS.fields_by_name['duration_until_decay']._options = None
_PARAMS.fields_by_name['duration_of_decay']._options = None
# @@protoc_insertion_point(module_scope)
