# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethermint/feemarket/v1/feemarket.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ethermint/feemarket/v1/feemarket.proto',
  package='ethermint.feemarket.v1',
  syntax='proto3',
  serialized_options=b'Z.github.com/tharsis/ethermint/x/feemarket/types',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n&ethermint/feemarket/v1/feemarket.proto\x12\x16\x65thermint.feemarket.v1\"\x92\x01\n\x06Params\x12\x13\n\x0bno_base_fee\x18\x01 \x01(\x08\x12#\n\x1b\x62\x61se_fee_change_denominator\x18\x02 \x01(\r\x12\x1d\n\x15\x65lasticity_multiplier\x18\x03 \x01(\r\x12\x18\n\x10initial_base_fee\x18\x04 \x01(\x03\x12\x15\n\renable_height\x18\x05 \x01(\x03\x42\x30Z.github.com/tharsis/ethermint/x/feemarket/typesb\x06proto3'
)




_PARAMS = _descriptor.Descriptor(
  name='Params',
  full_name='ethermint.feemarket.v1.Params',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='no_base_fee', full_name='ethermint.feemarket.v1.Params.no_base_fee', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='base_fee_change_denominator', full_name='ethermint.feemarket.v1.Params.base_fee_change_denominator', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='elasticity_multiplier', full_name='ethermint.feemarket.v1.Params.elasticity_multiplier', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='initial_base_fee', full_name='ethermint.feemarket.v1.Params.initial_base_fee', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enable_height', full_name='ethermint.feemarket.v1.Params.enable_height', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=213,
)

DESCRIPTOR.message_types_by_name['Params'] = _PARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Params = _reflection.GeneratedProtocolMessageType('Params', (_message.Message,), {
  'DESCRIPTOR' : _PARAMS,
  '__module__' : 'ethermint.feemarket.v1.feemarket_pb2'
  # @@protoc_insertion_point(class_scope:ethermint.feemarket.v1.Params)
  })
_sym_db.RegisterMessage(Params)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
