# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethermint/feemarket/v1/query.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from evmosproto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from evmosproto.google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from evmosproto.ethermint.feemarket.v1 import feemarket_pb2 as ethermint_dot_feemarket_dot_v1_dot_feemarket__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ethermint/feemarket/v1/query.proto',
  package='ethermint.feemarket.v1',
  syntax='proto3',
  serialized_options=b'Z.github.com/tharsis/ethermint/x/feemarket/types',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"ethermint/feemarket/v1/query.proto\x12\x16\x65thermint.feemarket.v1\x1a\x14gogoproto/gogo.proto\x1a\x1cgoogle/api/annotations.proto\x1a&ethermint/feemarket/v1/feemarket.proto\"\x14\n\x12QueryParamsRequest\"K\n\x13QueryParamsResponse\x12\x34\n\x06params\x18\x01 \x01(\x0b\x32\x1e.ethermint.feemarket.v1.ParamsB\x04\xc8\xde\x1f\x00\"\x15\n\x13QueryBaseFeeRequest\"X\n\x14QueryBaseFeeResponse\x12@\n\x08\x62\x61se_fee\x18\x01 \x01(\tB.\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Int\xc8\xde\x1f\x00\"\x16\n\x14QueryBlockGasRequest\"$\n\x15QueryBlockGasResponse\x12\x0b\n\x03gas\x18\x01 \x01(\x03\x32\xa7\x03\n\x05Query\x12\x83\x01\n\x06Params\x12*.ethermint.feemarket.v1.QueryParamsRequest\x1a+.ethermint.feemarket.v1.QueryParamsResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/feemarket/evm/v1/params\x12\x88\x01\n\x07\x42\x61seFee\x12+.ethermint.feemarket.v1.QueryBaseFeeRequest\x1a,.ethermint.feemarket.v1.QueryBaseFeeResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/feemarket/evm/v1/base_fee\x12\x8c\x01\n\x08\x42lockGas\x12,.ethermint.feemarket.v1.QueryBlockGasRequest\x1a-.ethermint.feemarket.v1.QueryBlockGasResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/feemarket/evm/v1/block_gasB0Z.github.com/tharsis/ethermint/x/feemarket/typesb\x06proto3'
  ,
  dependencies=[gogoproto_dot_gogo__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,ethermint_dot_feemarket_dot_v1_dot_feemarket__pb2.DESCRIPTOR,])




_QUERYPARAMSREQUEST = _descriptor.Descriptor(
  name='QueryParamsRequest',
  full_name='ethermint.feemarket.v1.QueryParamsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=174,
)


_QUERYPARAMSRESPONSE = _descriptor.Descriptor(
  name='QueryParamsResponse',
  full_name='ethermint.feemarket.v1.QueryParamsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='params', full_name='ethermint.feemarket.v1.QueryParamsResponse.params', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=251,
)


_QUERYBASEFEEREQUEST = _descriptor.Descriptor(
  name='QueryBaseFeeRequest',
  full_name='ethermint.feemarket.v1.QueryBaseFeeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=274,
)


_QUERYBASEFEERESPONSE = _descriptor.Descriptor(
  name='QueryBaseFeeResponse',
  full_name='ethermint.feemarket.v1.QueryBaseFeeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='base_fee', full_name='ethermint.feemarket.v1.QueryBaseFeeResponse.base_fee', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\332\336\037&github.com/cosmos/cosmos-sdk/types.Int\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=364,
)


_QUERYBLOCKGASREQUEST = _descriptor.Descriptor(
  name='QueryBlockGasRequest',
  full_name='ethermint.feemarket.v1.QueryBlockGasRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=366,
  serialized_end=388,
)


_QUERYBLOCKGASRESPONSE = _descriptor.Descriptor(
  name='QueryBlockGasResponse',
  full_name='ethermint.feemarket.v1.QueryBlockGasResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gas', full_name='ethermint.feemarket.v1.QueryBlockGasResponse.gas', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=390,
  serialized_end=426,
)

_QUERYPARAMSRESPONSE.fields_by_name['params'].message_type = ethermint_dot_feemarket_dot_v1_dot_feemarket__pb2._PARAMS
DESCRIPTOR.message_types_by_name['QueryParamsRequest'] = _QUERYPARAMSREQUEST
DESCRIPTOR.message_types_by_name['QueryParamsResponse'] = _QUERYPARAMSRESPONSE
DESCRIPTOR.message_types_by_name['QueryBaseFeeRequest'] = _QUERYBASEFEEREQUEST
DESCRIPTOR.message_types_by_name['QueryBaseFeeResponse'] = _QUERYBASEFEERESPONSE
DESCRIPTOR.message_types_by_name['QueryBlockGasRequest'] = _QUERYBLOCKGASREQUEST
DESCRIPTOR.message_types_by_name['QueryBlockGasResponse'] = _QUERYBLOCKGASRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QueryParamsRequest = _reflection.GeneratedProtocolMessageType('QueryParamsRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUERYPARAMSREQUEST,
  '__module__' : 'ethermint.feemarket.v1.query_pb2'
  # @@protoc_insertion_point(class_scope:ethermint.feemarket.v1.QueryParamsRequest)
  })
_sym_db.RegisterMessage(QueryParamsRequest)

QueryParamsResponse = _reflection.GeneratedProtocolMessageType('QueryParamsResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUERYPARAMSRESPONSE,
  '__module__' : 'ethermint.feemarket.v1.query_pb2'
  # @@protoc_insertion_point(class_scope:ethermint.feemarket.v1.QueryParamsResponse)
  })
_sym_db.RegisterMessage(QueryParamsResponse)

QueryBaseFeeRequest = _reflection.GeneratedProtocolMessageType('QueryBaseFeeRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUERYBASEFEEREQUEST,
  '__module__' : 'ethermint.feemarket.v1.query_pb2'
  # @@protoc_insertion_point(class_scope:ethermint.feemarket.v1.QueryBaseFeeRequest)
  })
_sym_db.RegisterMessage(QueryBaseFeeRequest)

QueryBaseFeeResponse = _reflection.GeneratedProtocolMessageType('QueryBaseFeeResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUERYBASEFEERESPONSE,
  '__module__' : 'ethermint.feemarket.v1.query_pb2'
  # @@protoc_insertion_point(class_scope:ethermint.feemarket.v1.QueryBaseFeeResponse)
  })
_sym_db.RegisterMessage(QueryBaseFeeResponse)

QueryBlockGasRequest = _reflection.GeneratedProtocolMessageType('QueryBlockGasRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUERYBLOCKGASREQUEST,
  '__module__' : 'ethermint.feemarket.v1.query_pb2'
  # @@protoc_insertion_point(class_scope:ethermint.feemarket.v1.QueryBlockGasRequest)
  })
_sym_db.RegisterMessage(QueryBlockGasRequest)

QueryBlockGasResponse = _reflection.GeneratedProtocolMessageType('QueryBlockGasResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUERYBLOCKGASRESPONSE,
  '__module__' : 'ethermint.feemarket.v1.query_pb2'
  # @@protoc_insertion_point(class_scope:ethermint.feemarket.v1.QueryBlockGasResponse)
  })
_sym_db.RegisterMessage(QueryBlockGasResponse)


DESCRIPTOR._options = None
_QUERYPARAMSRESPONSE.fields_by_name['params']._options = None
_QUERYBASEFEERESPONSE.fields_by_name['base_fee']._options = None

_QUERY = _descriptor.ServiceDescriptor(
  name='Query',
  full_name='ethermint.feemarket.v1.Query',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=429,
  serialized_end=852,
  methods=[
  _descriptor.MethodDescriptor(
    name='Params',
    full_name='ethermint.feemarket.v1.Query.Params',
    index=0,
    containing_service=None,
    input_type=_QUERYPARAMSREQUEST,
    output_type=_QUERYPARAMSRESPONSE,
    serialized_options=b'\202\323\344\223\002\032\022\030/feemarket/evm/v1/params',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='BaseFee',
    full_name='ethermint.feemarket.v1.Query.BaseFee',
    index=1,
    containing_service=None,
    input_type=_QUERYBASEFEEREQUEST,
    output_type=_QUERYBASEFEERESPONSE,
    serialized_options=b'\202\323\344\223\002\034\022\032/feemarket/evm/v1/base_fee',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='BlockGas',
    full_name='ethermint.feemarket.v1.Query.BlockGas',
    index=2,
    containing_service=None,
    input_type=_QUERYBLOCKGASREQUEST,
    output_type=_QUERYBLOCKGASRESPONSE,
    serialized_options=b'\202\323\344\223\002\035\022\033/feemarket/evm/v1/block_gas',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_QUERY)

DESCRIPTOR.services_by_name['Query'] = _QUERY

# @@protoc_insertion_point(module_scope)
