# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: evmos/vesting/v1/tx.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from evmosproto.google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from evmosproto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from evmosproto.cosmos.vesting.v1beta1 import vesting_pb2 as cosmos_dot_vesting_dot_v1beta1_dot_vesting__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='evmos/vesting/v1/tx.proto',
  package='evmos.vesting.v1',
  syntax='proto3',
  serialized_options=b'Z(github.com/tharsis/evmos/x/vesting/types',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19\x65vmos/vesting/v1/tx.proto\x12\x10\x65vmos.vesting.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x14gogoproto/gogo.proto\x1a$cosmos/vesting/v1beta1/vesting.proto\"\xb8\x02\n\x1fMsgCreateClawbackVestingAccount\x12-\n\x0c\x66rom_address\x18\x01 \x01(\tB\x17\xf2\xde\x1f\x13yaml:\"from_address\"\x12)\n\nto_address\x18\x02 \x01(\tB\x15\xf2\xde\x1f\x11yaml:\"to_address\"\x12)\n\nstart_time\x18\x03 \x01(\x03\x42\x15\xf2\xde\x1f\x11yaml:\"start_time\"\x12<\n\x0elockup_periods\x18\x04 \x03(\x0b\x32\x1e.cosmos.vesting.v1beta1.PeriodB\x04\xc8\xde\x1f\x00\x12=\n\x0fvesting_periods\x18\x05 \x03(\x0b\x32\x1e.cosmos.vesting.v1beta1.PeriodB\x04\xc8\xde\x1f\x00\x12\r\n\x05merge\x18\x06 \x01(\x08:\x04\xe8\xa0\x1f\x00\")\n\'MsgCreateClawbackVestingAccountResponse\"L\n\x0bMsgClawback\x12\x16\n\x0e\x66under_address\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x14\n\x0c\x64\x65st_address\x18\x03 \x01(\t\"\x15\n\x13MsgClawbackResponse2\xcb\x02\n\x03Msg\x12\xca\x01\n\x1c\x43reateClawbackVestingAccount\x12\x31.evmos.vesting.v1.MsgCreateClawbackVestingAccount\x1a\x39.evmos.vesting.v1.MsgCreateClawbackVestingAccountResponse\"<\x82\xd3\xe4\x93\x02\x36\x12\x34/evmos/vesting/v1/tx/create_clawback_vesting_account\x12w\n\x08\x43lawback\x12\x1d.evmos.vesting.v1.MsgClawback\x1a%.evmos.vesting.v1.MsgClawbackResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/evmos/vesting/v1/tx/clawbackB*Z(github.com/tharsis/evmos/x/vesting/typesb\x06proto3'
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,gogoproto_dot_gogo__pb2.DESCRIPTOR,cosmos_dot_vesting_dot_v1beta1_dot_vesting__pb2.DESCRIPTOR,])




_MSGCREATECLAWBACKVESTINGACCOUNT = _descriptor.Descriptor(
  name='MsgCreateClawbackVestingAccount',
  full_name='evmos.vesting.v1.MsgCreateClawbackVestingAccount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='from_address', full_name='evmos.vesting.v1.MsgCreateClawbackVestingAccount.from_address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\362\336\037\023yaml:\"from_address\"', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='to_address', full_name='evmos.vesting.v1.MsgCreateClawbackVestingAccount.to_address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\362\336\037\021yaml:\"to_address\"', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='evmos.vesting.v1.MsgCreateClawbackVestingAccount.start_time', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\362\336\037\021yaml:\"start_time\"', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lockup_periods', full_name='evmos.vesting.v1.MsgCreateClawbackVestingAccount.lockup_periods', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vesting_periods', full_name='evmos.vesting.v1.MsgCreateClawbackVestingAccount.vesting_periods', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='merge', full_name='evmos.vesting.v1.MsgCreateClawbackVestingAccount.merge', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\350\240\037\000',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=450,
)


_MSGCREATECLAWBACKVESTINGACCOUNTRESPONSE = _descriptor.Descriptor(
  name='MsgCreateClawbackVestingAccountResponse',
  full_name='evmos.vesting.v1.MsgCreateClawbackVestingAccountResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=452,
  serialized_end=493,
)


_MSGCLAWBACK = _descriptor.Descriptor(
  name='MsgClawback',
  full_name='evmos.vesting.v1.MsgClawback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='funder_address', full_name='evmos.vesting.v1.MsgClawback.funder_address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='address', full_name='evmos.vesting.v1.MsgClawback.address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dest_address', full_name='evmos.vesting.v1.MsgClawback.dest_address', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=495,
  serialized_end=571,
)


_MSGCLAWBACKRESPONSE = _descriptor.Descriptor(
  name='MsgClawbackResponse',
  full_name='evmos.vesting.v1.MsgClawbackResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=573,
  serialized_end=594,
)

_MSGCREATECLAWBACKVESTINGACCOUNT.fields_by_name['lockup_periods'].message_type = cosmos_dot_vesting_dot_v1beta1_dot_vesting__pb2._PERIOD
_MSGCREATECLAWBACKVESTINGACCOUNT.fields_by_name['vesting_periods'].message_type = cosmos_dot_vesting_dot_v1beta1_dot_vesting__pb2._PERIOD
DESCRIPTOR.message_types_by_name['MsgCreateClawbackVestingAccount'] = _MSGCREATECLAWBACKVESTINGACCOUNT
DESCRIPTOR.message_types_by_name['MsgCreateClawbackVestingAccountResponse'] = _MSGCREATECLAWBACKVESTINGACCOUNTRESPONSE
DESCRIPTOR.message_types_by_name['MsgClawback'] = _MSGCLAWBACK
DESCRIPTOR.message_types_by_name['MsgClawbackResponse'] = _MSGCLAWBACKRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MsgCreateClawbackVestingAccount = _reflection.GeneratedProtocolMessageType('MsgCreateClawbackVestingAccount', (_message.Message,), {
  'DESCRIPTOR' : _MSGCREATECLAWBACKVESTINGACCOUNT,
  '__module__' : 'evmos.vesting.v1.tx_pb2'
  # @@protoc_insertion_point(class_scope:evmos.vesting.v1.MsgCreateClawbackVestingAccount)
  })
_sym_db.RegisterMessage(MsgCreateClawbackVestingAccount)

MsgCreateClawbackVestingAccountResponse = _reflection.GeneratedProtocolMessageType('MsgCreateClawbackVestingAccountResponse', (_message.Message,), {
  'DESCRIPTOR' : _MSGCREATECLAWBACKVESTINGACCOUNTRESPONSE,
  '__module__' : 'evmos.vesting.v1.tx_pb2'
  # @@protoc_insertion_point(class_scope:evmos.vesting.v1.MsgCreateClawbackVestingAccountResponse)
  })
_sym_db.RegisterMessage(MsgCreateClawbackVestingAccountResponse)

MsgClawback = _reflection.GeneratedProtocolMessageType('MsgClawback', (_message.Message,), {
  'DESCRIPTOR' : _MSGCLAWBACK,
  '__module__' : 'evmos.vesting.v1.tx_pb2'
  # @@protoc_insertion_point(class_scope:evmos.vesting.v1.MsgClawback)
  })
_sym_db.RegisterMessage(MsgClawback)

MsgClawbackResponse = _reflection.GeneratedProtocolMessageType('MsgClawbackResponse', (_message.Message,), {
  'DESCRIPTOR' : _MSGCLAWBACKRESPONSE,
  '__module__' : 'evmos.vesting.v1.tx_pb2'
  # @@protoc_insertion_point(class_scope:evmos.vesting.v1.MsgClawbackResponse)
  })
_sym_db.RegisterMessage(MsgClawbackResponse)


DESCRIPTOR._options = None
_MSGCREATECLAWBACKVESTINGACCOUNT.fields_by_name['from_address']._options = None
_MSGCREATECLAWBACKVESTINGACCOUNT.fields_by_name['to_address']._options = None
_MSGCREATECLAWBACKVESTINGACCOUNT.fields_by_name['start_time']._options = None
_MSGCREATECLAWBACKVESTINGACCOUNT.fields_by_name['lockup_periods']._options = None
_MSGCREATECLAWBACKVESTINGACCOUNT.fields_by_name['vesting_periods']._options = None
_MSGCREATECLAWBACKVESTINGACCOUNT._options = None

_MSG = _descriptor.ServiceDescriptor(
  name='Msg',
  full_name='evmos.vesting.v1.Msg',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=597,
  serialized_end=928,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateClawbackVestingAccount',
    full_name='evmos.vesting.v1.Msg.CreateClawbackVestingAccount',
    index=0,
    containing_service=None,
    input_type=_MSGCREATECLAWBACKVESTINGACCOUNT,
    output_type=_MSGCREATECLAWBACKVESTINGACCOUNTRESPONSE,
    serialized_options=b'\202\323\344\223\0026\0224/evmos/vesting/v1/tx/create_clawback_vesting_account',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Clawback',
    full_name='evmos.vesting.v1.Msg.Clawback',
    index=1,
    containing_service=None,
    input_type=_MSGCLAWBACK,
    output_type=_MSGCLAWBACKRESPONSE,
    serialized_options=b'\202\323\344\223\002\037\022\035/evmos/vesting/v1/tx/clawback',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MSG)

DESCRIPTOR.services_by_name['Msg'] = _MSG

# @@protoc_insertion_point(module_scope)
