# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: evmos/vesting/v1/vesting.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from evmosproto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from evmosproto.cosmos.vesting.v1beta1 import vesting_pb2 as cosmos_dot_vesting_dot_v1beta1_dot_vesting__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='evmos/vesting/v1/vesting.proto',
  package='evmos.vesting.v1',
  syntax='proto3',
  serialized_options=b'Z(github.com/tharsis/evmos/x/vesting/types',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1e\x65vmos/vesting/v1/vesting.proto\x12\x10\x65vmos.vesting.v1\x1a\x14gogoproto/gogo.proto\x1a$cosmos/vesting/v1beta1/vesting.proto\"\x80\x03\n\x16\x43lawbackVestingAccount\x12N\n\x14\x62\x61se_vesting_account\x18\x01 \x01(\x0b\x32*.cosmos.vesting.v1beta1.BaseVestingAccountB\x04\xd0\xde\x1f\x01\x12\x31\n\x0e\x66under_address\x18\x02 \x01(\tB\x19\xf2\xde\x1f\x15yaml:\"funder_address\"\x12)\n\nstart_time\x18\x03 \x01(\x03\x42\x15\xf2\xde\x1f\x11yaml:\"start_time\"\x12U\n\x0elockup_periods\x18\x04 \x03(\x0b\x32\x1e.cosmos.vesting.v1beta1.PeriodB\x1d\xf2\xde\x1f\x15yaml:\"lockup_periods\"\xc8\xde\x1f\x00\x12W\n\x0fvesting_periods\x18\x05 \x03(\x0b\x32\x1e.cosmos.vesting.v1beta1.PeriodB\x1e\xf2\xde\x1f\x16yaml:\"vesting_periods\"\xc8\xde\x1f\x00:\x08\x88\xa0\x1f\x00\x98\xa0\x1f\x00\x42*Z(github.com/tharsis/evmos/x/vesting/typesb\x06proto3'
  ,
  dependencies=[gogoproto_dot_gogo__pb2.DESCRIPTOR,cosmos_dot_vesting_dot_v1beta1_dot_vesting__pb2.DESCRIPTOR,])




_CLAWBACKVESTINGACCOUNT = _descriptor.Descriptor(
  name='ClawbackVestingAccount',
  full_name='evmos.vesting.v1.ClawbackVestingAccount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='base_vesting_account', full_name='evmos.vesting.v1.ClawbackVestingAccount.base_vesting_account', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\320\336\037\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='funder_address', full_name='evmos.vesting.v1.ClawbackVestingAccount.funder_address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\362\336\037\025yaml:\"funder_address\"', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='evmos.vesting.v1.ClawbackVestingAccount.start_time', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\362\336\037\021yaml:\"start_time\"', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lockup_periods', full_name='evmos.vesting.v1.ClawbackVestingAccount.lockup_periods', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\362\336\037\025yaml:\"lockup_periods\"\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vesting_periods', full_name='evmos.vesting.v1.ClawbackVestingAccount.vesting_periods', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\362\336\037\026yaml:\"vesting_periods\"\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\210\240\037\000\230\240\037\000',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=497,
)

_CLAWBACKVESTINGACCOUNT.fields_by_name['base_vesting_account'].message_type = cosmos_dot_vesting_dot_v1beta1_dot_vesting__pb2._BASEVESTINGACCOUNT
_CLAWBACKVESTINGACCOUNT.fields_by_name['lockup_periods'].message_type = cosmos_dot_vesting_dot_v1beta1_dot_vesting__pb2._PERIOD
_CLAWBACKVESTINGACCOUNT.fields_by_name['vesting_periods'].message_type = cosmos_dot_vesting_dot_v1beta1_dot_vesting__pb2._PERIOD
DESCRIPTOR.message_types_by_name['ClawbackVestingAccount'] = _CLAWBACKVESTINGACCOUNT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClawbackVestingAccount = _reflection.GeneratedProtocolMessageType('ClawbackVestingAccount', (_message.Message,), {
  'DESCRIPTOR' : _CLAWBACKVESTINGACCOUNT,
  '__module__' : 'evmos.vesting.v1.vesting_pb2'
  # @@protoc_insertion_point(class_scope:evmos.vesting.v1.ClawbackVestingAccount)
  })
_sym_db.RegisterMessage(ClawbackVestingAccount)


DESCRIPTOR._options = None
_CLAWBACKVESTINGACCOUNT.fields_by_name['base_vesting_account']._options = None
_CLAWBACKVESTINGACCOUNT.fields_by_name['funder_address']._options = None
_CLAWBACKVESTINGACCOUNT.fields_by_name['start_time']._options = None
_CLAWBACKVESTINGACCOUNT.fields_by_name['lockup_periods']._options = None
_CLAWBACKVESTINGACCOUNT.fields_by_name['vesting_periods']._options = None
_CLAWBACKVESTINGACCOUNT._options = None
# @@protoc_insertion_point(module_scope)
