# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: evmos/intrarelayer/v1/intrarelayer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from evmosproto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from evmosproto.cosmos.bank.v1beta1 import bank_pb2 as cosmos_dot_bank_dot_v1beta1_dot_bank__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='evmos/intrarelayer/v1/intrarelayer.proto',
  package='evmos.intrarelayer.v1',
  syntax='proto3',
  serialized_options=b'Z-github.com/tharsis/evmos/x/intrarelayer/types',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n(evmos/intrarelayer/v1/intrarelayer.proto\x12\x15\x65vmos.intrarelayer.v1\x1a\x14gogoproto/gogo.proto\x1a\x1e\x63osmos/bank/v1beta1/bank.proto\"~\n\tTokenPair\x12\x15\n\rerc20_address\x18\x01 \x01(\t\x12\r\n\x05\x64\x65nom\x18\x02 \x01(\t\x12\x0f\n\x07\x65nabled\x18\x03 \x01(\x08\x12\x34\n\x0e\x63ontract_owner\x18\x04 \x01(\x0e\x32\x1c.evmos.intrarelayer.v1.Owner:\x04\xe8\xa0\x1f\x01\"w\n\x14RegisterCoinProposal\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x35\n\x08metadata\x18\x03 \x01(\x0b\x32\x1d.cosmos.bank.v1beta1.MetadataB\x04\xc8\xde\x1f\x00:\x04\xe8\xa0\x1f\x00\"W\n\x15RegisterERC20Proposal\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x14\n\x0c\x65rc20address\x18\x03 \x01(\t:\x04\xe8\xa0\x1f\x00\"S\n\x18ToggleTokenRelayProposal\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t:\x04\xe8\xa0\x1f\x01\"z\n\x1cUpdateTokenPairERC20Proposal\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x15\n\rerc20_address\x18\x03 \x01(\t\x12\x19\n\x11new_erc20_address\x18\x04 \x01(\t:\x04\xe8\xa0\x1f\x01*J\n\x05Owner\x12\x15\n\x11OWNER_UNSPECIFIED\x10\x00\x12\x10\n\x0cOWNER_MODULE\x10\x01\x12\x12\n\x0eOWNER_EXTERNAL\x10\x02\x1a\x04\x88\xa3\x1e\x00\x42/Z-github.com/tharsis/evmos/x/intrarelayer/typesb\x06proto3'
  ,
  dependencies=[gogoproto_dot_gogo__pb2.DESCRIPTOR,cosmos_dot_bank_dot_v1beta1_dot_bank__pb2.DESCRIPTOR,])

_OWNER = _descriptor.EnumDescriptor(
  name='Owner',
  full_name='evmos.intrarelayer.v1.Owner',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OWNER_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OWNER_MODULE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OWNER_EXTERNAL', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=b'\210\243\036\000',
  serialized_start=668,
  serialized_end=742,
)
_sym_db.RegisterEnumDescriptor(_OWNER)

Owner = enum_type_wrapper.EnumTypeWrapper(_OWNER)
OWNER_UNSPECIFIED = 0
OWNER_MODULE = 1
OWNER_EXTERNAL = 2



_TOKENPAIR = _descriptor.Descriptor(
  name='TokenPair',
  full_name='evmos.intrarelayer.v1.TokenPair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='erc20_address', full_name='evmos.intrarelayer.v1.TokenPair.erc20_address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='denom', full_name='evmos.intrarelayer.v1.TokenPair.denom', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enabled', full_name='evmos.intrarelayer.v1.TokenPair.enabled', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contract_owner', full_name='evmos.intrarelayer.v1.TokenPair.contract_owner', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\350\240\037\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=247,
)


_REGISTERCOINPROPOSAL = _descriptor.Descriptor(
  name='RegisterCoinProposal',
  full_name='evmos.intrarelayer.v1.RegisterCoinProposal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='evmos.intrarelayer.v1.RegisterCoinProposal.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='evmos.intrarelayer.v1.RegisterCoinProposal.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='evmos.intrarelayer.v1.RegisterCoinProposal.metadata', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\350\240\037\000',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=368,
)


_REGISTERERC20PROPOSAL = _descriptor.Descriptor(
  name='RegisterERC20Proposal',
  full_name='evmos.intrarelayer.v1.RegisterERC20Proposal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='evmos.intrarelayer.v1.RegisterERC20Proposal.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='evmos.intrarelayer.v1.RegisterERC20Proposal.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='erc20address', full_name='evmos.intrarelayer.v1.RegisterERC20Proposal.erc20address', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\350\240\037\000',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=370,
  serialized_end=457,
)


_TOGGLETOKENRELAYPROPOSAL = _descriptor.Descriptor(
  name='ToggleTokenRelayProposal',
  full_name='evmos.intrarelayer.v1.ToggleTokenRelayProposal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='evmos.intrarelayer.v1.ToggleTokenRelayProposal.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='evmos.intrarelayer.v1.ToggleTokenRelayProposal.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='token', full_name='evmos.intrarelayer.v1.ToggleTokenRelayProposal.token', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\350\240\037\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=459,
  serialized_end=542,
)


_UPDATETOKENPAIRERC20PROPOSAL = _descriptor.Descriptor(
  name='UpdateTokenPairERC20Proposal',
  full_name='evmos.intrarelayer.v1.UpdateTokenPairERC20Proposal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='evmos.intrarelayer.v1.UpdateTokenPairERC20Proposal.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='evmos.intrarelayer.v1.UpdateTokenPairERC20Proposal.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='erc20_address', full_name='evmos.intrarelayer.v1.UpdateTokenPairERC20Proposal.erc20_address', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='new_erc20_address', full_name='evmos.intrarelayer.v1.UpdateTokenPairERC20Proposal.new_erc20_address', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\350\240\037\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=544,
  serialized_end=666,
)

_TOKENPAIR.fields_by_name['contract_owner'].enum_type = _OWNER
_REGISTERCOINPROPOSAL.fields_by_name['metadata'].message_type = cosmos_dot_bank_dot_v1beta1_dot_bank__pb2._METADATA
DESCRIPTOR.message_types_by_name['TokenPair'] = _TOKENPAIR
DESCRIPTOR.message_types_by_name['RegisterCoinProposal'] = _REGISTERCOINPROPOSAL
DESCRIPTOR.message_types_by_name['RegisterERC20Proposal'] = _REGISTERERC20PROPOSAL
DESCRIPTOR.message_types_by_name['ToggleTokenRelayProposal'] = _TOGGLETOKENRELAYPROPOSAL
DESCRIPTOR.message_types_by_name['UpdateTokenPairERC20Proposal'] = _UPDATETOKENPAIRERC20PROPOSAL
DESCRIPTOR.enum_types_by_name['Owner'] = _OWNER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TokenPair = _reflection.GeneratedProtocolMessageType('TokenPair', (_message.Message,), {
  'DESCRIPTOR' : _TOKENPAIR,
  '__module__' : 'evmos.intrarelayer.v1.intrarelayer_pb2'
  # @@protoc_insertion_point(class_scope:evmos.intrarelayer.v1.TokenPair)
  })
_sym_db.RegisterMessage(TokenPair)

RegisterCoinProposal = _reflection.GeneratedProtocolMessageType('RegisterCoinProposal', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERCOINPROPOSAL,
  '__module__' : 'evmos.intrarelayer.v1.intrarelayer_pb2'
  # @@protoc_insertion_point(class_scope:evmos.intrarelayer.v1.RegisterCoinProposal)
  })
_sym_db.RegisterMessage(RegisterCoinProposal)

RegisterERC20Proposal = _reflection.GeneratedProtocolMessageType('RegisterERC20Proposal', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERERC20PROPOSAL,
  '__module__' : 'evmos.intrarelayer.v1.intrarelayer_pb2'
  # @@protoc_insertion_point(class_scope:evmos.intrarelayer.v1.RegisterERC20Proposal)
  })
_sym_db.RegisterMessage(RegisterERC20Proposal)

ToggleTokenRelayProposal = _reflection.GeneratedProtocolMessageType('ToggleTokenRelayProposal', (_message.Message,), {
  'DESCRIPTOR' : _TOGGLETOKENRELAYPROPOSAL,
  '__module__' : 'evmos.intrarelayer.v1.intrarelayer_pb2'
  # @@protoc_insertion_point(class_scope:evmos.intrarelayer.v1.ToggleTokenRelayProposal)
  })
_sym_db.RegisterMessage(ToggleTokenRelayProposal)

UpdateTokenPairERC20Proposal = _reflection.GeneratedProtocolMessageType('UpdateTokenPairERC20Proposal', (_message.Message,), {
  'DESCRIPTOR' : _UPDATETOKENPAIRERC20PROPOSAL,
  '__module__' : 'evmos.intrarelayer.v1.intrarelayer_pb2'
  # @@protoc_insertion_point(class_scope:evmos.intrarelayer.v1.UpdateTokenPairERC20Proposal)
  })
_sym_db.RegisterMessage(UpdateTokenPairERC20Proposal)


DESCRIPTOR._options = None
_OWNER._options = None
_TOKENPAIR._options = None
_REGISTERCOINPROPOSAL.fields_by_name['metadata']._options = None
_REGISTERCOINPROPOSAL._options = None
_REGISTERERC20PROPOSAL._options = None
_TOGGLETOKENRELAYPROPOSAL._options = None
_UPDATETOKENPAIRERC20PROPOSAL._options = None
# @@protoc_insertion_point(module_scope)
