# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: evmos/intrarelayer/v1/query.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from evmosproto.cosmos.base.query.v1beta1 import pagination_pb2 as cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2
from evmosproto.evmos.intrarelayer.v1 import genesis_pb2 as evmos_dot_intrarelayer_dot_v1_dot_genesis__pb2
from evmosproto.evmos.intrarelayer.v1 import intrarelayer_pb2 as evmos_dot_intrarelayer_dot_v1_dot_intrarelayer__pb2
from evmosproto.google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from evmosproto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='evmos/intrarelayer/v1/query.proto',
  package='evmos.intrarelayer.v1',
  syntax='proto3',
  serialized_options=b'Z-github.com/tharsis/evmos/x/intrarelayer/types',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!evmos/intrarelayer/v1/query.proto\x12\x15\x65vmos.intrarelayer.v1\x1a*cosmos/base/query/v1beta1/pagination.proto\x1a#evmos/intrarelayer/v1/genesis.proto\x1a(evmos/intrarelayer/v1/intrarelayer.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x14gogoproto/gogo.proto\"T\n\x16QueryTokenPairsRequest\x12:\n\npagination\x18\x01 \x01(\x0b\x32&.cosmos.base.query.v1beta1.PageRequest\"\x93\x01\n\x17QueryTokenPairsResponse\x12;\n\x0btoken_pairs\x18\x01 \x03(\x0b\x32 .evmos.intrarelayer.v1.TokenPairB\x04\xc8\xde\x1f\x00\x12;\n\npagination\x18\x02 \x01(\x0b\x32\'.cosmos.base.query.v1beta1.PageResponse\"&\n\x15QueryTokenPairRequest\x12\r\n\x05token\x18\x01 \x01(\t\"T\n\x16QueryTokenPairResponse\x12:\n\ntoken_pair\x18\x01 \x01(\x0b\x32 .evmos.intrarelayer.v1.TokenPairB\x04\xc8\xde\x1f\x00\"\x14\n\x12QueryParamsRequest\"J\n\x13QueryParamsResponse\x12\x33\n\x06params\x18\x01 \x01(\x0b\x32\x1d.evmos.intrarelayer.v1.ParamsB\x04\xc8\xde\x1f\x00\x32\xc9\x03\n\x05Query\x12\x97\x01\n\nTokenPairs\x12-.evmos.intrarelayer.v1.QueryTokenPairsRequest\x1a..evmos.intrarelayer.v1.QueryTokenPairsResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/evmos/intrarelayer/v1/token_pairs\x12\x9c\x01\n\tTokenPair\x12,.evmos.intrarelayer.v1.QueryTokenPairRequest\x1a-.evmos.intrarelayer.v1.QueryTokenPairResponse\"2\x82\xd3\xe4\x93\x02,\x12*/evmos/intrarelayer/v1/token_pairs/{token}\x12\x86\x01\n\x06Params\x12).evmos.intrarelayer.v1.QueryParamsRequest\x1a*.evmos.intrarelayer.v1.QueryParamsResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/evmos/intrarelayer/v1/paramsB/Z-github.com/tharsis/evmos/x/intrarelayer/typesb\x06proto3'
  ,
  dependencies=[cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2.DESCRIPTOR,evmos_dot_intrarelayer_dot_v1_dot_genesis__pb2.DESCRIPTOR,evmos_dot_intrarelayer_dot_v1_dot_intrarelayer__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,gogoproto_dot_gogo__pb2.DESCRIPTOR,])




_QUERYTOKENPAIRSREQUEST = _descriptor.Descriptor(
  name='QueryTokenPairsRequest',
  full_name='evmos.intrarelayer.v1.QueryTokenPairsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pagination', full_name='evmos.intrarelayer.v1.QueryTokenPairsRequest.pagination', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=235,
  serialized_end=319,
)


_QUERYTOKENPAIRSRESPONSE = _descriptor.Descriptor(
  name='QueryTokenPairsResponse',
  full_name='evmos.intrarelayer.v1.QueryTokenPairsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='token_pairs', full_name='evmos.intrarelayer.v1.QueryTokenPairsResponse.token_pairs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pagination', full_name='evmos.intrarelayer.v1.QueryTokenPairsResponse.pagination', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=322,
  serialized_end=469,
)


_QUERYTOKENPAIRREQUEST = _descriptor.Descriptor(
  name='QueryTokenPairRequest',
  full_name='evmos.intrarelayer.v1.QueryTokenPairRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='evmos.intrarelayer.v1.QueryTokenPairRequest.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=471,
  serialized_end=509,
)


_QUERYTOKENPAIRRESPONSE = _descriptor.Descriptor(
  name='QueryTokenPairResponse',
  full_name='evmos.intrarelayer.v1.QueryTokenPairResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='token_pair', full_name='evmos.intrarelayer.v1.QueryTokenPairResponse.token_pair', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=511,
  serialized_end=595,
)


_QUERYPARAMSREQUEST = _descriptor.Descriptor(
  name='QueryParamsRequest',
  full_name='evmos.intrarelayer.v1.QueryParamsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=597,
  serialized_end=617,
)


_QUERYPARAMSRESPONSE = _descriptor.Descriptor(
  name='QueryParamsResponse',
  full_name='evmos.intrarelayer.v1.QueryParamsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='params', full_name='evmos.intrarelayer.v1.QueryParamsResponse.params', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=619,
  serialized_end=693,
)

_QUERYTOKENPAIRSREQUEST.fields_by_name['pagination'].message_type = cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2._PAGEREQUEST
_QUERYTOKENPAIRSRESPONSE.fields_by_name['token_pairs'].message_type = evmos_dot_intrarelayer_dot_v1_dot_intrarelayer__pb2._TOKENPAIR
_QUERYTOKENPAIRSRESPONSE.fields_by_name['pagination'].message_type = cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2._PAGERESPONSE
_QUERYTOKENPAIRRESPONSE.fields_by_name['token_pair'].message_type = evmos_dot_intrarelayer_dot_v1_dot_intrarelayer__pb2._TOKENPAIR
_QUERYPARAMSRESPONSE.fields_by_name['params'].message_type = evmos_dot_intrarelayer_dot_v1_dot_genesis__pb2._PARAMS
DESCRIPTOR.message_types_by_name['QueryTokenPairsRequest'] = _QUERYTOKENPAIRSREQUEST
DESCRIPTOR.message_types_by_name['QueryTokenPairsResponse'] = _QUERYTOKENPAIRSRESPONSE
DESCRIPTOR.message_types_by_name['QueryTokenPairRequest'] = _QUERYTOKENPAIRREQUEST
DESCRIPTOR.message_types_by_name['QueryTokenPairResponse'] = _QUERYTOKENPAIRRESPONSE
DESCRIPTOR.message_types_by_name['QueryParamsRequest'] = _QUERYPARAMSREQUEST
DESCRIPTOR.message_types_by_name['QueryParamsResponse'] = _QUERYPARAMSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QueryTokenPairsRequest = _reflection.GeneratedProtocolMessageType('QueryTokenPairsRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUERYTOKENPAIRSREQUEST,
  '__module__' : 'evmos.intrarelayer.v1.query_pb2'
  # @@protoc_insertion_point(class_scope:evmos.intrarelayer.v1.QueryTokenPairsRequest)
  })
_sym_db.RegisterMessage(QueryTokenPairsRequest)

QueryTokenPairsResponse = _reflection.GeneratedProtocolMessageType('QueryTokenPairsResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUERYTOKENPAIRSRESPONSE,
  '__module__' : 'evmos.intrarelayer.v1.query_pb2'
  # @@protoc_insertion_point(class_scope:evmos.intrarelayer.v1.QueryTokenPairsResponse)
  })
_sym_db.RegisterMessage(QueryTokenPairsResponse)

QueryTokenPairRequest = _reflection.GeneratedProtocolMessageType('QueryTokenPairRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUERYTOKENPAIRREQUEST,
  '__module__' : 'evmos.intrarelayer.v1.query_pb2'
  # @@protoc_insertion_point(class_scope:evmos.intrarelayer.v1.QueryTokenPairRequest)
  })
_sym_db.RegisterMessage(QueryTokenPairRequest)

QueryTokenPairResponse = _reflection.GeneratedProtocolMessageType('QueryTokenPairResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUERYTOKENPAIRRESPONSE,
  '__module__' : 'evmos.intrarelayer.v1.query_pb2'
  # @@protoc_insertion_point(class_scope:evmos.intrarelayer.v1.QueryTokenPairResponse)
  })
_sym_db.RegisterMessage(QueryTokenPairResponse)

QueryParamsRequest = _reflection.GeneratedProtocolMessageType('QueryParamsRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUERYPARAMSREQUEST,
  '__module__' : 'evmos.intrarelayer.v1.query_pb2'
  # @@protoc_insertion_point(class_scope:evmos.intrarelayer.v1.QueryParamsRequest)
  })
_sym_db.RegisterMessage(QueryParamsRequest)

QueryParamsResponse = _reflection.GeneratedProtocolMessageType('QueryParamsResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUERYPARAMSRESPONSE,
  '__module__' : 'evmos.intrarelayer.v1.query_pb2'
  # @@protoc_insertion_point(class_scope:evmos.intrarelayer.v1.QueryParamsResponse)
  })
_sym_db.RegisterMessage(QueryParamsResponse)


DESCRIPTOR._options = None
_QUERYTOKENPAIRSRESPONSE.fields_by_name['token_pairs']._options = None
_QUERYTOKENPAIRRESPONSE.fields_by_name['token_pair']._options = None
_QUERYPARAMSRESPONSE.fields_by_name['params']._options = None

_QUERY = _descriptor.ServiceDescriptor(
  name='Query',
  full_name='evmos.intrarelayer.v1.Query',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=696,
  serialized_end=1153,
  methods=[
  _descriptor.MethodDescriptor(
    name='TokenPairs',
    full_name='evmos.intrarelayer.v1.Query.TokenPairs',
    index=0,
    containing_service=None,
    input_type=_QUERYTOKENPAIRSREQUEST,
    output_type=_QUERYTOKENPAIRSRESPONSE,
    serialized_options=b'\202\323\344\223\002$\022\"/evmos/intrarelayer/v1/token_pairs',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TokenPair',
    full_name='evmos.intrarelayer.v1.Query.TokenPair',
    index=1,
    containing_service=None,
    input_type=_QUERYTOKENPAIRREQUEST,
    output_type=_QUERYTOKENPAIRRESPONSE,
    serialized_options=b'\202\323\344\223\002,\022*/evmos/intrarelayer/v1/token_pairs/{token}',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Params',
    full_name='evmos.intrarelayer.v1.Query.Params',
    index=2,
    containing_service=None,
    input_type=_QUERYPARAMSREQUEST,
    output_type=_QUERYPARAMSRESPONSE,
    serialized_options=b'\202\323\344\223\002\037\022\035/evmos/intrarelayer/v1/params',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_QUERY)

DESCRIPTOR.services_by_name['Query'] = _QUERY

# @@protoc_insertion_point(module_scope)
