# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: evmos/intrarelayer/v1/tx.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from evmosproto.google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from evmosproto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from evmosproto.cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='evmos/intrarelayer/v1/tx.proto',
  package='evmos.intrarelayer.v1',
  syntax='proto3',
  serialized_options=b'Z-github.com/tharsis/evmos/x/intrarelayer/types',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1e\x65vmos/intrarelayer/v1/tx.proto\x12\x15\x65vmos.intrarelayer.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x14gogoproto/gogo.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto\"a\n\x0eMsgConvertCoin\x12-\n\x04\x63oin\x18\x01 \x01(\x0b\x32\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00\x12\x10\n\x08receiver\x18\x02 \x01(\t\x12\x0e\n\x06sender\x18\x03 \x01(\t\"\x18\n\x16MsgConvertCoinResponse\"\x8d\x01\n\x0fMsgConvertERC20\x12\x18\n\x10\x63ontract_address\x18\x01 \x01(\t\x12>\n\x06\x61mount\x18\x02 \x01(\tB.\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Int\xc8\xde\x1f\x00\x12\x10\n\x08receiver\x18\x03 \x01(\t\x12\x0e\n\x06sender\x18\x04 \x01(\t\"\x19\n\x17MsgConvertERC20Response2\xb5\x02\n\x03Msg\x12\x93\x01\n\x0b\x43onvertCoin\x12%.evmos.intrarelayer.v1.MsgConvertCoin\x1a-.evmos.intrarelayer.v1.MsgConvertCoinResponse\".\x82\xd3\xe4\x93\x02(\x12&/evmos/intrarelayer/v1/tx/convert_coin\x12\x97\x01\n\x0c\x43onvertERC20\x12&.evmos.intrarelayer.v1.MsgConvertERC20\x1a..evmos.intrarelayer.v1.MsgConvertERC20Response\"/\x82\xd3\xe4\x93\x02)\x12\'/evmos/intrarelayer/v1/tx/convert_erc20B/Z-github.com/tharsis/evmos/x/intrarelayer/typesb\x06proto3'
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,gogoproto_dot_gogo__pb2.DESCRIPTOR,cosmos_dot_base_dot_v1beta1_dot_coin__pb2.DESCRIPTOR,])




_MSGCONVERTCOIN = _descriptor.Descriptor(
  name='MsgConvertCoin',
  full_name='evmos.intrarelayer.v1.MsgConvertCoin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='coin', full_name='evmos.intrarelayer.v1.MsgConvertCoin.coin', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='receiver', full_name='evmos.intrarelayer.v1.MsgConvertCoin.receiver', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sender', full_name='evmos.intrarelayer.v1.MsgConvertCoin.sender', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=238,
)


_MSGCONVERTCOINRESPONSE = _descriptor.Descriptor(
  name='MsgConvertCoinResponse',
  full_name='evmos.intrarelayer.v1.MsgConvertCoinResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=264,
)


_MSGCONVERTERC20 = _descriptor.Descriptor(
  name='MsgConvertERC20',
  full_name='evmos.intrarelayer.v1.MsgConvertERC20',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='contract_address', full_name='evmos.intrarelayer.v1.MsgConvertERC20.contract_address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='amount', full_name='evmos.intrarelayer.v1.MsgConvertERC20.amount', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\332\336\037&github.com/cosmos/cosmos-sdk/types.Int\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='receiver', full_name='evmos.intrarelayer.v1.MsgConvertERC20.receiver', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sender', full_name='evmos.intrarelayer.v1.MsgConvertERC20.sender', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=408,
)


_MSGCONVERTERC20RESPONSE = _descriptor.Descriptor(
  name='MsgConvertERC20Response',
  full_name='evmos.intrarelayer.v1.MsgConvertERC20Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=410,
  serialized_end=435,
)

_MSGCONVERTCOIN.fields_by_name['coin'].message_type = cosmos_dot_base_dot_v1beta1_dot_coin__pb2._COIN
DESCRIPTOR.message_types_by_name['MsgConvertCoin'] = _MSGCONVERTCOIN
DESCRIPTOR.message_types_by_name['MsgConvertCoinResponse'] = _MSGCONVERTCOINRESPONSE
DESCRIPTOR.message_types_by_name['MsgConvertERC20'] = _MSGCONVERTERC20
DESCRIPTOR.message_types_by_name['MsgConvertERC20Response'] = _MSGCONVERTERC20RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MsgConvertCoin = _reflection.GeneratedProtocolMessageType('MsgConvertCoin', (_message.Message,), {
  'DESCRIPTOR' : _MSGCONVERTCOIN,
  '__module__' : 'evmos.intrarelayer.v1.tx_pb2'
  # @@protoc_insertion_point(class_scope:evmos.intrarelayer.v1.MsgConvertCoin)
  })
_sym_db.RegisterMessage(MsgConvertCoin)

MsgConvertCoinResponse = _reflection.GeneratedProtocolMessageType('MsgConvertCoinResponse', (_message.Message,), {
  'DESCRIPTOR' : _MSGCONVERTCOINRESPONSE,
  '__module__' : 'evmos.intrarelayer.v1.tx_pb2'
  # @@protoc_insertion_point(class_scope:evmos.intrarelayer.v1.MsgConvertCoinResponse)
  })
_sym_db.RegisterMessage(MsgConvertCoinResponse)

MsgConvertERC20 = _reflection.GeneratedProtocolMessageType('MsgConvertERC20', (_message.Message,), {
  'DESCRIPTOR' : _MSGCONVERTERC20,
  '__module__' : 'evmos.intrarelayer.v1.tx_pb2'
  # @@protoc_insertion_point(class_scope:evmos.intrarelayer.v1.MsgConvertERC20)
  })
_sym_db.RegisterMessage(MsgConvertERC20)

MsgConvertERC20Response = _reflection.GeneratedProtocolMessageType('MsgConvertERC20Response', (_message.Message,), {
  'DESCRIPTOR' : _MSGCONVERTERC20RESPONSE,
  '__module__' : 'evmos.intrarelayer.v1.tx_pb2'
  # @@protoc_insertion_point(class_scope:evmos.intrarelayer.v1.MsgConvertERC20Response)
  })
_sym_db.RegisterMessage(MsgConvertERC20Response)


DESCRIPTOR._options = None
_MSGCONVERTCOIN.fields_by_name['coin']._options = None
_MSGCONVERTERC20.fields_by_name['amount']._options = None

_MSG = _descriptor.ServiceDescriptor(
  name='Msg',
  full_name='evmos.intrarelayer.v1.Msg',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=438,
  serialized_end=747,
  methods=[
  _descriptor.MethodDescriptor(
    name='ConvertCoin',
    full_name='evmos.intrarelayer.v1.Msg.ConvertCoin',
    index=0,
    containing_service=None,
    input_type=_MSGCONVERTCOIN,
    output_type=_MSGCONVERTCOINRESPONSE,
    serialized_options=b'\202\323\344\223\002(\022&/evmos/intrarelayer/v1/tx/convert_coin',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ConvertERC20',
    full_name='evmos.intrarelayer.v1.Msg.ConvertERC20',
    index=1,
    containing_service=None,
    input_type=_MSGCONVERTERC20,
    output_type=_MSGCONVERTERC20RESPONSE,
    serialized_options=b'\202\323\344\223\002)\022\'/evmos/intrarelayer/v1/tx/convert_erc20',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MSG)

DESCRIPTOR.services_by_name['Msg'] = _MSG

# @@protoc_insertion_point(module_scope)
