# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: evmos/inflation/v1/genesis.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from evmosproto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from evmosproto.evmos.inflation.v1 import inflation_pb2 as evmos_dot_inflation_dot_v1_dot_inflation__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='evmos/inflation/v1/genesis.proto',
  package='evmos.inflation.v1',
  syntax='proto3',
  serialized_options=b'Z*github.com/tharsis/evmos/x/inflation/types',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n evmos/inflation/v1/genesis.proto\x12\x12\x65vmos.inflation.v1\x1a\x14gogoproto/gogo.proto\x1a\"evmos/inflation/v1/inflation.proto\"\x85\x01\n\x0cGenesisState\x12\x30\n\x06params\x18\x01 \x01(\x0b\x32\x1a.evmos.inflation.v1.ParamsB\x04\xc8\xde\x1f\x00\x12\x0e\n\x06period\x18\x02 \x01(\x04\x12\x18\n\x10\x65poch_identifier\x18\x03 \x01(\t\x12\x19\n\x11\x65pochs_per_period\x18\x04 \x01(\x03\"\xc6\x01\n\x06Params\x12\x12\n\nmint_denom\x18\x01 \x01(\t\x12Q\n\x17\x65xponential_calculation\x18\x02 \x01(\x0b\x32*.evmos.inflation.v1.ExponentialCalculationB\x04\xc8\xde\x1f\x00\x12O\n\x16inflation_distribution\x18\x03 \x01(\x0b\x32).evmos.inflation.v1.InflationDistributionB\x04\xc8\xde\x1f\x00:\x04\x98\xa0\x1f\x00\x42,Z*github.com/tharsis/evmos/x/inflation/typesb\x06proto3'
  ,
  dependencies=[gogoproto_dot_gogo__pb2.DESCRIPTOR,evmos_dot_inflation_dot_v1_dot_inflation__pb2.DESCRIPTOR,])




_GENESISSTATE = _descriptor.Descriptor(
  name='GenesisState',
  full_name='evmos.inflation.v1.GenesisState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='params', full_name='evmos.inflation.v1.GenesisState.params', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='period', full_name='evmos.inflation.v1.GenesisState.period', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='epoch_identifier', full_name='evmos.inflation.v1.GenesisState.epoch_identifier', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='epochs_per_period', full_name='evmos.inflation.v1.GenesisState.epochs_per_period', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=248,
)


_PARAMS = _descriptor.Descriptor(
  name='Params',
  full_name='evmos.inflation.v1.Params',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mint_denom', full_name='evmos.inflation.v1.Params.mint_denom', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exponential_calculation', full_name='evmos.inflation.v1.Params.exponential_calculation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='inflation_distribution', full_name='evmos.inflation.v1.Params.inflation_distribution', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'\230\240\037\000',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=449,
)

_GENESISSTATE.fields_by_name['params'].message_type = _PARAMS
_PARAMS.fields_by_name['exponential_calculation'].message_type = evmos_dot_inflation_dot_v1_dot_inflation__pb2._EXPONENTIALCALCULATION
_PARAMS.fields_by_name['inflation_distribution'].message_type = evmos_dot_inflation_dot_v1_dot_inflation__pb2._INFLATIONDISTRIBUTION
DESCRIPTOR.message_types_by_name['GenesisState'] = _GENESISSTATE
DESCRIPTOR.message_types_by_name['Params'] = _PARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenesisState = _reflection.GeneratedProtocolMessageType('GenesisState', (_message.Message,), {
  'DESCRIPTOR' : _GENESISSTATE,
  '__module__' : 'evmos.inflation.v1.genesis_pb2'
  # @@protoc_insertion_point(class_scope:evmos.inflation.v1.GenesisState)
  })
_sym_db.RegisterMessage(GenesisState)

Params = _reflection.GeneratedProtocolMessageType('Params', (_message.Message,), {
  'DESCRIPTOR' : _PARAMS,
  '__module__' : 'evmos.inflation.v1.genesis_pb2'
  # @@protoc_insertion_point(class_scope:evmos.inflation.v1.Params)
  })
_sym_db.RegisterMessage(Params)


DESCRIPTOR._options = None
_GENESISSTATE.fields_by_name['params']._options = None
_PARAMS.fields_by_name['exponential_calculation']._options = None
_PARAMS.fields_by_name['inflation_distribution']._options = None
_PARAMS._options = None
# @@protoc_insertion_point(module_scope)
