# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: evmos/inflation/v1/inflation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from evmosproto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='evmos/inflation/v1/inflation.proto',
  package='evmos.inflation.v1',
  syntax='proto3',
  serialized_options=b'Z*github.com/tharsis/evmos/x/inflation/types',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"evmos/inflation/v1/inflation.proto\x12\x12\x65vmos.inflation.v1\x1a\x14gogoproto/gogo.proto\"\xf2\x01\n\x15InflationDistribution\x12G\n\x0fstaking_rewards\x18\x01 \x01(\tB.\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xc8\xde\x1f\x00\x12H\n\x10usage_incentives\x18\x02 \x01(\tB.\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xc8\xde\x1f\x00\x12\x46\n\x0e\x63ommunity_pool\x18\x03 \x01(\tB.\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xc8\xde\x1f\x00\"\xd7\x02\n\x16\x45xponentialCalculation\x12\x39\n\x01\x61\x18\x01 \x01(\tB.\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xc8\xde\x1f\x00\x12\x39\n\x01r\x18\x02 \x01(\tB.\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xc8\xde\x1f\x00\x12\x39\n\x01\x63\x18\x03 \x01(\tB.\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xc8\xde\x1f\x00\x12\x46\n\x0e\x62onding_target\x18\x04 \x01(\tB.\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xc8\xde\x1f\x00\x12\x44\n\x0cmax_variance\x18\x05 \x01(\tB.\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xc8\xde\x1f\x00\x42,Z*github.com/tharsis/evmos/x/inflation/typesb\x06proto3'
  ,
  dependencies=[gogoproto_dot_gogo__pb2.DESCRIPTOR,])




_INFLATIONDISTRIBUTION = _descriptor.Descriptor(
  name='InflationDistribution',
  full_name='evmos.inflation.v1.InflationDistribution',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='staking_rewards', full_name='evmos.inflation.v1.InflationDistribution.staking_rewards', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='usage_incentives', full_name='evmos.inflation.v1.InflationDistribution.usage_incentives', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='community_pool', full_name='evmos.inflation.v1.InflationDistribution.community_pool', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=323,
)


_EXPONENTIALCALCULATION = _descriptor.Descriptor(
  name='ExponentialCalculation',
  full_name='evmos.inflation.v1.ExponentialCalculation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='evmos.inflation.v1.ExponentialCalculation.a', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='r', full_name='evmos.inflation.v1.ExponentialCalculation.r', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='c', full_name='evmos.inflation.v1.ExponentialCalculation.c', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bonding_target', full_name='evmos.inflation.v1.ExponentialCalculation.bonding_target', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_variance', full_name='evmos.inflation.v1.ExponentialCalculation.max_variance', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=326,
  serialized_end=669,
)

DESCRIPTOR.message_types_by_name['InflationDistribution'] = _INFLATIONDISTRIBUTION
DESCRIPTOR.message_types_by_name['ExponentialCalculation'] = _EXPONENTIALCALCULATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InflationDistribution = _reflection.GeneratedProtocolMessageType('InflationDistribution', (_message.Message,), {
  'DESCRIPTOR' : _INFLATIONDISTRIBUTION,
  '__module__' : 'evmos.inflation.v1.inflation_pb2'
  # @@protoc_insertion_point(class_scope:evmos.inflation.v1.InflationDistribution)
  })
_sym_db.RegisterMessage(InflationDistribution)

ExponentialCalculation = _reflection.GeneratedProtocolMessageType('ExponentialCalculation', (_message.Message,), {
  'DESCRIPTOR' : _EXPONENTIALCALCULATION,
  '__module__' : 'evmos.inflation.v1.inflation_pb2'
  # @@protoc_insertion_point(class_scope:evmos.inflation.v1.ExponentialCalculation)
  })
_sym_db.RegisterMessage(ExponentialCalculation)


DESCRIPTOR._options = None
_INFLATIONDISTRIBUTION.fields_by_name['staking_rewards']._options = None
_INFLATIONDISTRIBUTION.fields_by_name['usage_incentives']._options = None
_INFLATIONDISTRIBUTION.fields_by_name['community_pool']._options = None
_EXPONENTIALCALCULATION.fields_by_name['a']._options = None
_EXPONENTIALCALCULATION.fields_by_name['r']._options = None
_EXPONENTIALCALCULATION.fields_by_name['c']._options = None
_EXPONENTIALCALCULATION.fields_by_name['bonding_target']._options = None
_EXPONENTIALCALCULATION.fields_by_name['max_variance']._options = None
# @@protoc_insertion_point(module_scope)
