# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: evmos/erc20/v1/genesis.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from evmosproto.evmos.erc20.v1 import erc20_pb2 as evmos_dot_erc20_dot_v1_dot_erc20__pb2
from evmosproto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='evmos/erc20/v1/genesis.proto',
  package='evmos.erc20.v1',
  syntax='proto3',
  serialized_options=b'Z&github.com/tharsis/evmos/x/erc20/types',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1c\x65vmos/erc20/v1/genesis.proto\x12\x0e\x65vmos.erc20.v1\x1a\x1a\x65vmos/erc20/v1/erc20.proto\x1a\x14gogoproto/gogo.proto\"r\n\x0cGenesisState\x12,\n\x06params\x18\x01 \x01(\x0b\x32\x16.evmos.erc20.v1.ParamsB\x04\xc8\xde\x1f\x00\x12\x34\n\x0btoken_pairs\x18\x02 \x03(\x0b\x32\x19.evmos.erc20.v1.TokenPairB\x04\xc8\xde\x1f\x00\"J\n\x06Params\x12\x14\n\x0c\x65nable_erc20\x18\x01 \x01(\x08\x12*\n\x0f\x65nable_evm_hook\x18\x02 \x01(\x08\x42\x11\xe2\xde\x1f\rEnableEVMHookB(Z&github.com/tharsis/evmos/x/erc20/typesb\x06proto3'
  ,
  dependencies=[evmos_dot_erc20_dot_v1_dot_erc20__pb2.DESCRIPTOR,gogoproto_dot_gogo__pb2.DESCRIPTOR,])




_GENESISSTATE = _descriptor.Descriptor(
  name='GenesisState',
  full_name='evmos.erc20.v1.GenesisState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='params', full_name='evmos.erc20.v1.GenesisState.params', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='token_pairs', full_name='evmos.erc20.v1.GenesisState.token_pairs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=212,
)


_PARAMS = _descriptor.Descriptor(
  name='Params',
  full_name='evmos.erc20.v1.Params',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='enable_erc20', full_name='evmos.erc20.v1.Params.enable_erc20', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enable_evm_hook', full_name='evmos.erc20.v1.Params.enable_evm_hook', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\342\336\037\rEnableEVMHook', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=288,
)

_GENESISSTATE.fields_by_name['params'].message_type = _PARAMS
_GENESISSTATE.fields_by_name['token_pairs'].message_type = evmos_dot_erc20_dot_v1_dot_erc20__pb2._TOKENPAIR
DESCRIPTOR.message_types_by_name['GenesisState'] = _GENESISSTATE
DESCRIPTOR.message_types_by_name['Params'] = _PARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenesisState = _reflection.GeneratedProtocolMessageType('GenesisState', (_message.Message,), {
  'DESCRIPTOR' : _GENESISSTATE,
  '__module__' : 'evmos.erc20.v1.genesis_pb2'
  # @@protoc_insertion_point(class_scope:evmos.erc20.v1.GenesisState)
  })
_sym_db.RegisterMessage(GenesisState)

Params = _reflection.GeneratedProtocolMessageType('Params', (_message.Message,), {
  'DESCRIPTOR' : _PARAMS,
  '__module__' : 'evmos.erc20.v1.genesis_pb2'
  # @@protoc_insertion_point(class_scope:evmos.erc20.v1.Params)
  })
_sym_db.RegisterMessage(Params)


DESCRIPTOR._options = None
_GENESISSTATE.fields_by_name['params']._options = None
_GENESISSTATE.fields_by_name['token_pairs']._options = None
_PARAMS.fields_by_name['enable_evm_hook']._options = None
# @@protoc_insertion_point(module_scope)
