# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethermint/evm/v1/genesis.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from evmosproto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from evmosproto.ethermint.evm.v1 import evm_pb2 as ethermint_dot_evm_dot_v1_dot_evm__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ethermint/evm/v1/genesis.proto',
  package='ethermint.evm.v1',
  syntax='proto3',
  serialized_options=b'Z(github.com/tharsis/ethermint/x/evm/types',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1e\x65thermint/evm/v1/genesis.proto\x12\x10\x65thermint.evm.v1\x1a\x14gogoproto/gogo.proto\x1a\x1a\x65thermint/evm/v1/evm.proto\"\xc6\x01\n\x0cGenesisState\x12\x38\n\x08\x61\x63\x63ounts\x18\x01 \x03(\x0b\x32 .ethermint.evm.v1.GenesisAccountB\x04\xc8\xde\x1f\x00\x12.\n\x06params\x18\x03 \x01(\x0b\x32\x18.ethermint.evm.v1.ParamsB\x04\xc8\xde\x1f\x00\x12L\n\x08txs_logs\x18\x04 \x03(\x0b\x32!.ethermint.evm.v1.TransactionLogsB\x17\xf2\xde\x1f\x0fyaml:\"txs_logs\"\xc8\xde\x1f\x00\"j\n\x0eGenesisAccount\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x39\n\x07storage\x18\x03 \x03(\x0b\x32\x17.ethermint.evm.v1.StateB\x0f\xc8\xde\x1f\x00\xaa\xdf\x1f\x07StorageB*Z(github.com/tharsis/ethermint/x/evm/typesb\x06proto3'
  ,
  dependencies=[gogoproto_dot_gogo__pb2.DESCRIPTOR,ethermint_dot_evm_dot_v1_dot_evm__pb2.DESCRIPTOR,])




_GENESISSTATE = _descriptor.Descriptor(
  name='GenesisState',
  full_name='ethermint.evm.v1.GenesisState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='accounts', full_name='ethermint.evm.v1.GenesisState.accounts', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='params', full_name='ethermint.evm.v1.GenesisState.params', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='txs_logs', full_name='ethermint.evm.v1.GenesisState.txs_logs', index=2,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\362\336\037\017yaml:\"txs_logs\"\310\336\037\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=301,
)


_GENESISACCOUNT = _descriptor.Descriptor(
  name='GenesisAccount',
  full_name='ethermint.evm.v1.GenesisAccount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='ethermint.evm.v1.GenesisAccount.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='ethermint.evm.v1.GenesisAccount.code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='storage', full_name='ethermint.evm.v1.GenesisAccount.storage', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\310\336\037\000\252\337\037\007Storage', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=409,
)

_GENESISSTATE.fields_by_name['accounts'].message_type = _GENESISACCOUNT
_GENESISSTATE.fields_by_name['params'].message_type = ethermint_dot_evm_dot_v1_dot_evm__pb2._PARAMS
_GENESISSTATE.fields_by_name['txs_logs'].message_type = ethermint_dot_evm_dot_v1_dot_evm__pb2._TRANSACTIONLOGS
_GENESISACCOUNT.fields_by_name['storage'].message_type = ethermint_dot_evm_dot_v1_dot_evm__pb2._STATE
DESCRIPTOR.message_types_by_name['GenesisState'] = _GENESISSTATE
DESCRIPTOR.message_types_by_name['GenesisAccount'] = _GENESISACCOUNT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenesisState = _reflection.GeneratedProtocolMessageType('GenesisState', (_message.Message,), {
  'DESCRIPTOR' : _GENESISSTATE,
  '__module__' : 'ethermint.evm.v1.genesis_pb2'
  # @@protoc_insertion_point(class_scope:ethermint.evm.v1.GenesisState)
  })
_sym_db.RegisterMessage(GenesisState)

GenesisAccount = _reflection.GeneratedProtocolMessageType('GenesisAccount', (_message.Message,), {
  'DESCRIPTOR' : _GENESISACCOUNT,
  '__module__' : 'ethermint.evm.v1.genesis_pb2'
  # @@protoc_insertion_point(class_scope:ethermint.evm.v1.GenesisAccount)
  })
_sym_db.RegisterMessage(GenesisAccount)


DESCRIPTOR._options = None
_GENESISSTATE.fields_by_name['accounts']._options = None
_GENESISSTATE.fields_by_name['params']._options = None
_GENESISSTATE.fields_by_name['txs_logs']._options = None
_GENESISACCOUNT.fields_by_name['storage']._options = None
# @@protoc_insertion_point(module_scope)
